"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
    python3 setup.py py2app --iconfile <filename>
"""

from setuptools import setup


APP = ['SpotifyTimer.py']
VERSION = '0.1.0'
DATA_FILES = ['logo.png']
OPTIONS = {"iconfile" : "SpotifyTimer_icon.icns", # path to the icon for the Application
           "plist" : {"NSHumanReadableCopyright" : "© 2023 Jules Pyke"} # copyright seen in MacOS 'Get Info' menu
           }
AUTHOR = 'Jules Pyke'
EMAIL = 'info@golively.tv'
DESCRIPTION = 'Countdown timer to pause Spotify'


setup(
    app=APP,
    version=VERSION,
    author=AUTHOR,
    author_email=EMAIL,
    description=DESCRIPTION,
    long_description=open('README.md').read(),
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
